export const sroutesPayload = {
    update: {
        name: "", 
        vehicles_type_id: "",
        starting_point: "",
        ending_point: "",
        distance: "",
        duration: "",
        is_ac: "",
        day_off: [],
        start_date: "",
        price: "",
        departure: "",
        arrivals: "",
        duration: "",
        status: ""
    },
    store: {
        name: "", 
        vehicles_type_id: "",
        starting_point: "",
        ending_point: "",
        distance: "",
        duration: "",
        is_ac: "1",
        day_off: [],
        start_date: "",
        price: "",
        departure: "",
        arrivals: "",
        duration: "",
        status: ""
    },
    columnsName: 'sroutesColumns',
    columns: [
        { id: "id", label: "Id", minWidth: 60 },
        { id: "name", label: "Name", minWidth: 100 },
        { id: "vehicles_type_id", label: "Vehicles Type", minWidth: 100 },
        { id: "starting_point", label: "Starting Point", minWidth: 100 },
        { id: "ending_point", label: "Ending Point", minWidth: 100 },
        { id: "distance", label: "Distance", minWidth: 100 },
        { id: "duration", label: "Duration", minWidth: 100 },
        { id: "is_ac", label: "AC", minWidth: 100 },
        { id: "day_off", label: "Day Off", minWidth: 100 },
        { id: "start_date", label: "Start Date", minWidth: 100 },
        { id: "price", label: "Price", minWidth: 100 },
        { id: "departure", label: "Departure", minWidth: 100 },
        { id: "arrivals", label: "Arrivals", minWidth: 100 },
        { id: "status", label: "Status", minWidth: 100 },

        { id: "created_by", label: "Created By", minWidth: 100 },
        { id: "updated_by", label: "Updated By", minWidth: 100 },
        { id: "created_at", label: "Created At", minWidth: 100 },
        { id: "updated_at", label: "Updated At", minWidth: 100 },

        { id: "option", label: "Option", minWidth: 100 },
    ],
    paginateParams: {
        page: 1,
        per_page: 10,
        columns: "name,vehiclesType,startingPoint,endingPoint,distance,duration,is_ac,dayOff,startDate,price,departure,arrivals,duration",
        search: "",
        order: "id",
        sort: "ASC",
        value: "",
        start_date: "",
        end_date: "",
        is_speicial: 1
    },
};
